pagopa/azure-pipeline-templates

templates/rest-healthcheck/README.md, templates/rest-healthcheck/template.yaml
this PR adds these parameters
1. **endpointType**: set public or private. Set to public if not necessary to deploy a container instance
1. **headers**: specify custom headers, for example secrets as azure pipeline secret variable
With custom headers we can do an authenticated request against public functions.
=> [#175919444] Add public endpoints

templates/rest-healthcheck/README.md, templates/rest-healthcheck/template.yaml
this PR add checks on rest response and also fix an issue when `headers` param is empty
=> [#175934270] Add checks on rest response

templates/rest-healthcheck/README.md
Updated README after its `public` use for `io-pay`
=> update readme healthcheck

templates/rest-healthcheck/template.yaml
- Moved to mcr.microsoft.com/azure-cli trying to fix Healthcheck error occurring while deploying eucovidcert function
=> Moved to mcr.microsoft.com/azure-cli

templates/terraform-aws-apply/README.md, templates/terraform-aws-apply/template.yaml, templates/terraform-aws-plan/README.md, templates/terraform-aws-plan/template.yaml
=> Template to run terraform plan in aws

templates/node-github-release/template.yaml
Added two steps into node-github-release
- update helm version
- update openapi version
To have same experience with maven and node project 
---
=> [node-github-release] Added Steps to update helm and openapi versions

.devops/test-development-pipelines.yaml, README.md
- rename test pipeline to test development pipelines
- add include folders to avoid run of this pipeline for other templates not related
---
=> test development pipelines: exclude folders not related

templates/node-job-setup/README.md, templates/terraform-plan/template.yaml
=> Minor change

.github/workflows/pr-title.yml, .github/workflows/release.yml
=> feat: Fix-release-action

.github/workflows/pr-title.yml, .github/workflows/release.yml
=> feat: Fix release branch

.github/workflows/pr-title.yml, .github/workflows/release.yml, .releaserc.json
=> chore: Add Release RC for semantic version 

.pre-commit-config.yaml
=> chore: Pre-commit fix

README.md, templates/terraform-aws-plan/README.md
=> fix: Minor fix

README.md, templates/terraform-aws-plan/template.yaml
Better readme with new templates and link for the pipelines
---
=> docs: Better readme

templates/node-github-release/template.yaml
fix node-github-release
- Fix helm version
- Fix commit: now the template create a single commit with `package.json`, `helm/values-*.yaml` and `openapi/*.json`
@pasqualespica and I found a bug with this template. The helm version wasn't updated.
---
=> fix: Node Template

templates/terraform-apply/README.md, templates/terraform-apply/template.yaml, templates/terraform-plan/README.md, templates/terraform-plan/template.yaml
- added kubernetes kubeconfig creation for terraform
- added check parameters
Allow terraform to run with kubernetes resources
---
=> feat: DEVOPS-492-cstar-idpay-creazione-deploy-pipeline

templates/maven-github-release/template.yaml, templates/node-github-release/template.yaml
=> feat: Update chart version and app version

.devops/test-development-pipelines.yaml
=> chore: Remove exclude from test (ignored by include)

templates/maven-github-current-version/README.md, templates/maven-github-current-version/template.yaml, templates/node-github-current-version/README.md, templates/node-github-current-version/template.yaml
=> feat: Add current version for node and maven projects

templates/deploy-release-decision/README.md, templates/deploy-release-decision/template.yaml
=> feat: Add deploy release decision

templates/maven-github-release/template.yaml, templates/node-github-release/template.yaml
=> fix: Bump release for openapi yaml/yml

templates/deploy-release-decision/README.md, templates/deploy-release-decision/template.yaml, templates/docker-release/README.md, templates/docker-release/template.yaml
=> feat: Add docker build

templates/helm-microservice-chart-setup/README.md, templates/helm-microservice-chart-setup/template.yaml
=> feat: Add Setup helm microservice-chart

templates/helm-microservice-chart-deploy/README.md, templates/helm-microservice-chart-deploy/template.yaml
=> feat: Add helm release

templates/maven-github-release/template.yaml
List all files pom.xml from project and add all to git after maven update version
---
=> fix: Add all .pom files to git after new version

templates/helm-microservice-chart-deploy/README.md, templates/helm-microservice-chart-deploy/template.yaml
- updated doc for  template
- updated doc for readme
Help documentation
---
=> chore: Fix docs helm-microservice-chart

scripts/azdo-generate-kubeconfig.sh, templates/terraform-apply/template.yaml, templates/terraform-plan-apply/README.md, templates/terraform-plan-apply/template.yaml, templates/terraform-plan/README.md, templates/terraform-plan/template.yaml
- created plan-apply template to simply the writing of deploy pipeline
- better variables names for apply and plan 
- better documentation
created plan-apply template to simply the writing of deploy pipeline
---
=> breaking: Added template terraform-plan-apply to simplify the pipelines

templates/docker-release/template.yaml, templates/helm-microservice-chart-deploy/template.yaml
The purpose of this PR is to add Docker file name parameter ( default `Dockerfile` ) in to `docker-release` template
---
=> feat: NOD-46 creazione helm

templates/docker-release/template.yaml
=> feat: Add DOCKERCONTEXT

templates/helm-microservice-chart-setup/template.yaml
modified helm setup pipeline to use locally scoped variable DEPLOY_VERSION
---
=> feat: Fix DEPLOY_VERSION to use template var

templates/sbt-github-release/template.yaml
=> feat: Sbt release no env declared

templates/helm-microservice-chart-deploy/template.yaml
Added parameter COMMAND in templates/helm-microservice-chart-deploy/template.yaml (defaults to "upgrade") to add the ability to change the behavior of the **HelmDeploy@0** task.
E.g. passing command "uninstall" will uninstall the helm deploy from kubernetes 
---
=> feat: Added parameter COMMAND in helm-microservice-chart-deploy template

templates/terraform-setup/template.yaml
Now terraform setup show more message to understand if everithing was ok
---
=> fix: Terraform setup improved

templates/terraform-setup/template.yaml, templates/terraform-summarize/README.md, templates/terraform-summarize/template.yaml
=> feat: Added-terraform-summarize

templates/terraform-plan/README.md, templates/terraform-plan/template.yaml
- added summarize for plan, this is an option and not mandatory
- the summarize is optional and the template works with the previous configuration
Have more info about the plans
---
=> feat: Improved tf-plan-with-summary

templates/terraform-plan/template.yaml
=> fix: Removed Draw from summarize

templates/terraform-summarize/README.md, templates/terraform-summarize/template.yaml
Update tf summarize to version 0.3.7
---
=> feat: Update TF summarize version v0.3.7

templates/terraform-summarize/README.md, templates/terraform-summarize/template.yaml
Summarize doesn't support zip file anymore
---
=> fix: Changed summarize zip to tar.gz

templates/terraform-plan/template.yaml, templates/terraform-summarize/README.md, templates/terraform-summarize/template.yaml
Summarize now deprated all the zip files
---
=> fix: Summarize use tar.gz as package

templates/postgres-flexible-failover/README.md, templates/postgres-flexible-failover/template.yaml
=> feat: Postgres failover pipeline

templates/postgres-flexible-failover/README.md, templates/postgres-flexible-failover/template.yaml
=> feat: Updated postgres failover pipeline

templates/terraform-apply/template.yaml, templates/terraform-plan/template.yaml
Working dir can be different from src, so now is mandatory as parameter
---
=> feat: TF Apply/Plan working_dir is mandatory

templates/helm-microservice-chart-deploy-tree/README.md, templates/helm-microservice-chart-deploy-tree/template.yaml, templates/helm-microservice-chart-setup/template.yaml
Added a new template to wrap helm setup and helm deploy, incorporating namespace and app version variable read from values.yaml file
Standardize the helm deployment management, basing it on a separate helm chart repository containing only charts and values for each app/environment combination for a given project
---
=> feat: Help setup deploy template

templates/helm-microservice-chart-deploy-tree/README.md, templates/helm-microservice-chart-deploy-tree/template.yaml
=> feat: Fix template parameters

templates/helm-microservice-chart-deploy-tree/template.yaml
=> feat: Removed repo name

templates/helm-microservice-chart-deploy-tree/template.yaml
=> feat: Added env on deploy stage

templates/helm-microservice-chart-deploy-tree/template.yaml
=> fix: Job name replace

templates/node-github-release/template.yaml
=> fix: Pre-release node-github-release

templates/helm-microservice-chart-deploy-tree/template.yaml
=> feat: Management of the release name variable

templates/terraform-plan-apply/template.yaml, templates/terraform-setup/template.yaml
=> feat: Fix apply template

templates/apim-set-values/README.md, templates/apim-set-values/template.yaml
=> feat: Added apim values set template

templates/apim-get-values/README.md, templates/apim-get-values/template.yaml
=> feat: Apim get values

templates/azure-kubeconfig-generator/template.yaml, templates/terraform-apply/template.yaml, templates/terraform-plan-apply/template.yaml, templates/terraform-plan/template.yaml, templates/terraform-setup/README.md, templates/terraform-setup/template.yaml
=> feat: Add support two aks clusters

templates/helm-microservice-chart-deploy-tree/template.yaml, templates/helm-microservice-chart-deploy/template.yaml
=> feat: Add force deploy helm

templates/terraform-apply/template.yaml
=> feat: Fix plan_sc on second cluster

templates/availability-publisher/template-step.yaml
=> feat: Fix script path
